### ISSUE TITLE
Inline 

### ISSUE THREAD

**Issue by pmqs** [raku-community-modules/Inline-C#5]
Just built & Installed Perl6 2015.01\* on a Linux 32-bit Ubuntu.

```
$ perl6 -v
This is perl6 version 2015.01 built on MoarVM version 2015.01
```

Trying to get **Inline** in place so I can run **Compress::Zlib**. So downloaded **Inline** from git, unpacked & tried to install as follows

```
$ panda install --nodeps .
==> Installing Inline from a local directory '.'
==> Fetching Inline
==> Building Inline
Compiling lib/Inline/C.pm to mbc
Compiling lib/Inline.pm to mbc
==> Testing Inline
This type cannot unbox to a native integer
  in method postcircumfix:<( )> at     /home/paul/perl/perl6/rakudo/languages/perl6/lib/NativeCall.pm6:139
  in method postcircumfix:<( )> at /linux-shared/base/perl/perl6/tmp/p6-Inline-C-master/.panda-work/1423424082_1/lib/Inline/C.pm:50
  in block <unit> at t/c.t:18
t/c.t .. 
Dubious, test returned 255 (wstat 65280, 0xff00)
Failed 1/1 subtests 
```

Apologies in advance if I've missed something fundamental.

Paul

**Comment by pmqs** [comment]
Think this one gets filed under "32-bit perl6 isn't working as well as it should - please come back later".
All worked fine with a 64-bit install. 
Think this ticket can be closed.

**Comment by FROGGS** [comment]
NativeCall got fixed in a dev branch and will land soon, when this fixes this issue I'll close it.

**Comment by azawawi** [comment]
How about closing it now? 👍
